
print("What is your name?")
name = input()
print("What is your orginization?")
org = input()
print("What is your form of contact?")
contact = input()
print("What is your access tier?")
access = input()
print("What is your issuer?")
issuer = input()
print("+-------------------------------------------------+")
print("|                         KIOSK TEAM 1 ACCESS     |")
print("|-------------------------------------------------|")
print("| ATTENDEE : "+name.ljust(37) + "|")
print("| ORG : "+org.ljust(42) + "|")
print("| CONTACT : "+contact.ljust(38) + "|")
print("| ACCESS : "+access.ljust(39) + "|")
print("| ISSUER : "+issuer.ljust(39) + "|")
print("+-------------------------------------------------+")